databaseChangeLog:
  - include:
      file: config/liquibase/changelog/1669699108_added_entity_Department.yaml
      relativeToChangelogFile: false
  - include:
      file: config/liquibase/changelog/1669699108_added_entity_constraints_Department.yaml
      relativeToChangelogFile: false