spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/department;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: rivc
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/rivc
      client:
        registration:
          oidc:
            client-id: rivc-client
            client-secret: changeit
            scope: openid,profile
