databaseChangeLog:
  - changeSet:
      id: 1669978133-1
      author: kevin
      changes:
          - createSequence:
              sequenceName: SEQUENCE_GENERATOR
              startValue: 50
              incrementBy: 50
